// Car list
const FETCH_CARS = 'FETCH_CARS';
const FETCH_CARS_SUCCESS = 'FETCH_CARS_SUCCESS';
const FETCH_CARS_FAILURE = 'FETCH_CARS_FAILURE';

// Get specific car
const FETCH_CAR = 'FETCH_CAR';
const FETCH_CAR_SUCCESS = 'FETCH_CAR_SUCCESS';
const FETCH_CAR_FAILURE = 'FETCH_CAR_FAILURE';

// Post car
const POST_CARS = 'POST_CARS';
const POST_CARS_SUCCESS = 'POST_CARS_SUCCESS';
const POST_CARS_FAILURE = 'POST_CARS_FAILURE';

// Cars update
const UPDATE_CARS = 'UPDATE_CARS';
const UPDATE_CARS_SUCCESS = 'UPDATE_CARS_SUCCESS';
const UPDATE_CARS_FAILURE = 'UPDATE_CARS_FAILURE';

// Delete cars
const DELETE_CARS = 'DELETE_CARS';
const DELETE_CARS_SUCCESS = 'DELETE_CARS_SUCCESS';
const DELETE_CARS_FAILURE = 'DELETE_CARS_FAILURE';

export default {
  FETCH_CARS,
  FETCH_CARS_SUCCESS,
  FETCH_CARS_FAILURE,
  FETCH_CAR,
  FETCH_CAR_FAILURE,
  FETCH_CAR_SUCCESS,
  POST_CARS,
  POST_CARS_SUCCESS,
  POST_CARS_FAILURE,
  UPDATE_CARS,
  UPDATE_CARS_SUCCESS,
  UPDATE_CARS_FAILURE,
  DELETE_CARS,
  DELETE_CARS_SUCCESS,
  DELETE_CARS_FAILURE
};
